Assignment 2/mysurveys/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
resources :answers
resources :questions
resources :responses
resources :surveys
resources :takens

    root to: "users#index"
  end

      resources :surveys

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :grids, :only => [:index, :create, :show]


  get 'welcome/index'
  

  root 'welcome#index'

  get 'takesurvey/fill/:id/' => 'takesurvey#fill', :as => 'takesurvey'
 
  get 'jsonout/show/:id/' => 'jsonout#show'
 
  get 'jsonout/showall/' => 'jsonout#showall'

  get 'jsonout/index/' => 'jsonout#index'

  get 'jsonout/stats/:id'  => 'jsonout#stats' , :as => 'stats'

  get 'jsonout/question/:id'  => 'jsonout#question'

  get 'adminpage' => 'jsonout#indexusers' , :as => 'users'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Assignment 2/mysurveys/app/models/survey.rb
class Survey < ApplicationRecord
	
	has_many :questions, inverse_of: :survey , dependent: :destroy

	has_many :takens, inverse_of: :survey , dependent: :destroy

	accepts_nested_attributes_for :questions,
									reject_if: proc {|attributes| attributes['content'].blank? },
									allow_destroy: true

	validates :name,
				presence: true
	def to_s
		name
	end
end

Assignment 2/mysurveys/app/controllers/admin/surveys_controller.rb
module Admin
  class SurveysController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Survey.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Survey.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

Assignment 2/mysurveys/app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

    before_action :authenticate_admin , only: [ :show,:create,:new,:edit , :index , :destroy]
    
  def authenticate_admin
    # TODO Add authentication logic here.
      redirect_to root_url unless current_user.try(:admin)
  end

  def index
    @surveys = Survey.all
  end

  def show
    @survey = Survey.find(params[:id])
  end

  def new
    @survey = Survey.new
  end

  def edit
    @survey = Survey.find(params[:id])
  end

  def create
    @survey = Survey.new(survey_params)
      if @survey.save
        return redirect_to @survey, notice: 'Survey was successfully created.'
      else
        render :new
        return
      end
  end

  def update
    @survey = Survey.find(params[:id])
    @pre = Rails.application.routes.recognize_path(request.referrer)
    @currentUser = current_user.id

    if @pre[:controller] != "takesurvey"
  
      @survey.takens.destroy_all
      @survey.questions.each do |q|
        q.answers.each do |a|
              a.responses.destroy_all
          end
      end

    end

      if @survey.update(survey_params)
        if @pre[:controller] == "takesurvey"
              @taken = Taken.new(user_id: @currentUser , survey_id: @survey.id)
              @taken.save
              return redirect_to controller: 'welcome' , action: 'index' , notice: 'Survey was successfully Taken.' 
        end

        return redirect_to @survey, notice: 'Survey was successfully updated.'
      else
        render :edit
        return
      end
  end

  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy
    return redirect_to surveys_url, notice: 'Survey was successfully destroyed.'
  end

  private

    def survey_params
      params.require(:survey).permit(:name,questions_attributes: [:id,:content,:_destroy,answers_attributes: [:id,:content,:_destroy,responses_attributes: [:id,:content,:user_id,:_destroy]]])
    end

end

Assignment 2/mysurveys/app/helpers/surveys_helper.rb
module SurveysHelper
end

Assignment 2/mysurveys/app/views/surveys/_form.html.erb
<%= nested_form_for @survey do |f| %>

  <% if survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name , :placeholder => "Survey Name Here" %>
  </div>

<%= f.fields_for :questions do |qb| %>

<div class="container">  <%= qb.text_field :content , :placeholder => "Question Here" %>


          <%= qb.fields_for :answers do |qa| %>
            <div class="container"> <%= qa.text_field :content , :placeholder => "Answer Here" %>

             <div class="center" style="padding:10px"><%= qa.link_to_remove "Remove this answer",:class => 'waves-effect waves-light btn center' %><br></div>

             </div>
              
          <% end %>
          <br>
           <div class="center"><%= qb.link_to_add "Add a answer", :answers ,:class => 'waves-effect waves-light btn center'%></div>
          <br>
                      </div>

      <br>
  <div class="center"><%= qb.link_to_remove "Remove this question",:class => 'waves-effect waves-light btn center' %></div>

<% end %>
<%= f.link_to_add "Add a question", :questions ,:class => 'waves-effect waves-light btn center'%>

<br>

  <div class="actions center">
<%= f.submit "Submit", :class => 'red btn center' %>
  </div>
<% end %>

Assignment 2/mysurveys/app/views/surveys/edit.html.erb
<div class="container">
<h1>Editing Survey</h1>

<%= render 'form', survey: @survey %>
<br>
<div class="center">
<%= link_to 'Show', @survey ,:class => 'orange waves-effect waves-light btn center'%>
<%= link_to 'Back', surveys_path ,:class => ' orange waves-effect waves-light btn center'%>
</div>
</div>

Assignment 2/mysurveys/app/views/surveys/index.html.erb
<div class="container">

<h1 class="center">Surveys</h1>

      <table class="highlight bordered responsive-table centered">
        <thead>
          <tr>
              <th>Name</th>
              <th>Show</th>
              <th>Edit</th>
              <th>Delete</th>
          </tr>
        </thead>
  
  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.name %></td>
        <td><%= link_to 'Show', survey %> <i class="fa fa-file-text" aria-hidden="true"></i></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %> <i class="fa fa-pencil-square-o" aria-hidden="true"></i></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %> <i class="fa fa-trash" aria-hidden="true"></i></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>
<div class="center"><%= link_to 'Create a New Survey', new_survey_path , :class => 'waves-effect waves-light btn center' %></div>
<br>
</div>

Assignment 2/mysurveys/app/views/surveys/new.html.erb
<div class="container">
<h1>New Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Back', surveys_path ,:class => 'orange waves-effect waves-light btn center'%>
</div>

Assignment 2/mysurveys/app/views/surveys/show.html.erb
<div class="container">

<h2 class="center">Showing Survey - <%= @survey.name %></h2>

<% i=0 %>
<h1> Questions </h1>
<% if @survey.questions.any? %>
 	<% @survey.questions.each do |question| %>
 		<% i+=1 %>
 		<h4><%= i %>. <%= question.content %></h4>
 		<h5>Answers: </h5><br>
 		<ul class="collection">
 			<% question.answers.each do |answer| %>
 			<li class="collection-item"> <%= answer.content %></li>
 			<% end %>
 		</ul>
 		
 	<% end %>

<% else %>
<p>
<h3 class="center">None Available</h3>
</p>
<%end%>

<div class="center">
<%= link_to 'Edit', edit_survey_path(@survey) ,:class => 'waves-effect waves-light btn center' %>
<%= link_to 'Back', surveys_path ,:class => 'waves-effect waves-light btn center' %>
</div>
</div>