Assignment 2/mysurveys/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
resources :answers
resources :questions
resources :responses
resources :surveys
resources :takens

    root to: "users#index"
  end

      resources :surveys

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :grids, :only => [:index, :create, :show]


  get 'welcome/index'
  

  root 'welcome#index'

  get 'takesurvey/fill/:id/' => 'takesurvey#fill', :as => 'takesurvey'
 
  get 'jsonout/show/:id/' => 'jsonout#show'
 
  get 'jsonout/showall/' => 'jsonout#showall'

  get 'jsonout/index/' => 'jsonout#index'

  get 'jsonout/stats/:id'  => 'jsonout#stats' , :as => 'stats'

  get 'jsonout/question/:id'  => 'jsonout#question'

  get 'adminpage' => 'jsonout#indexusers' , :as => 'users'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Assignment 2/mysurveys/app/controllers/jsonout_controller.rb
class JsonoutController < ApplicationController

    before_action :authenticate_admin
    
    def authenticate_admin
      # TODO Add authentication logic here.
        redirect_to root_url unless current_user.try(:admin)
    end

	def show
		@survey = Survey.find(params[:id])
		@alreadytaken = Taken.where("survey_id = ?" , @survey.id).all
	end

	def showall
		@surveys = Survey.all
		@alreadytaken = Hash.new()
		@surveys.each do |survey|
			@alreadytaken[survey.id] = (Taken.where("survey_id = ?" , survey.id).all).size
		end
	end

	def index
		@surveys = Survey.all
	end


	def stats
		@survey = Survey.find(params[:id])
		@alreadytaken = Taken.where("survey_id = ?" , @survey.id).all
	end

	def question
		@question = Question.find(params[:id])
		@info = Hash.new()
		@question.answers.each do |answer|
			count = 0
				answer.responses.each do |response|
					if answer.content.split(':')[0] == "radio" 
						if response.content.eql?("1")
							count += 1
						end
					elsif answer.content.split(':')[0] == "check" 
						if response.content.eql?("1")
							count += 1
						end
					end
				end
			@info[answer.id] = count
		end
	end

	def indexusers
    	@users_grid = UsersGrid.new(params[:users_grid]) do |scope|
     		 scope.page(params[:page])
    	end
    	    render :layout => false     

	end

end

Assignment 2/mysurveys/app/helpers/jsonout_helper.rb
module JsonoutHelper
end

Assignment 2/mysurveys/app/views/jsonout/index.html.erb
<script type="text/javascript">

function drawChart() {
    $.getJSON("http://localhost:3000/jsonout/showall.json", function (json) { // callback function which gets called when your request completes. 
        new Morris.Bar ({
   element: 'survey_chart',

    data: json,
    xkey: 'SurveyName',
    ykeys: ['SurveyCount'],
    labels: ['Count'],
});
    });
}

</script>

<!-- Must PUT ON TOP  -->
<% colorarr = ["blue-grey darken-1","black","red accent-2","deep-purple accent-4","brown darken-1"] %>

<body onload="drawChart()">
	<div class="container">

    <h1 class="center">Graph</h1>
       <div id="survey_chart"></div>
        
        <h2 class="center">Detailed Stats</h2><br>

          <div class="row">

            <% @surveys.each do |survey| %>
                       <div class="col s12 m6">
          <div class="card <%= colorarr[rand(0..4)]%>">
                 <div class="card-content white-text">
                      <span class="card-title"><%= survey.name %></span>
            </div>
            <div class="card-action">
            <%= link_to "See Stats" , stats_path(survey.id) %>
            </div>
          </div>
          </div>
               

            <% end %>
            </div>

       </div>

</body>

Assignment 2/mysurveys/app/views/jsonout/indexusers.html.erb
<style type="text/css">
	.container 
	{
		overflow: hidden		
	}
</style>
<div class="container">
<h3>Users Grid</h3>

<div class="left">
  <%= datagrid_form_for @users_grid, url: users_path %>


  <div class='total'>Total: <%= @users_grid.assets.total_count %></div>
  <%= datagrid_table(@users_grid) %>
  <%= paginate @users_grid.assets %>
</div>
</div>

Assignment 2/mysurveys/app/views/jsonout/stats.html.erb
<script type="text/javascript">

function drawChart(my_var) {
    $.getJSON("http://localhost:3000/jsonout/question/"+ my_var +".json", function (json) { // callback function which gets called when your request completes. 
        Morris.Donut({
            element: my_var,
            data: json // use returned data to plot the graph
        });
    });
}

</script>

<!-- Must PUT ON TOP  -->

<div class="container">
<h1 class="center">Survey - <%= @survey.name %></h1>
<h5>Number of Users - <%= @alreadytaken.size %></h5>

<h5>Survey ID - <%= @survey.id %> </h5>
            
<% @survey.questions.each do |question| %>
      <h4>Question - <%= question.content %></h4>
            <% flag = 0 %>
        <h5>Answers</h5>
        <% question.answers.each do |answer| %>
                <% count = 0 %>
              <% if answer.content.split(':')[0] != "check" and answer.content.split(':')[0] != "radio" %>
                <table class="highlight bordered responsive-table centered">
                      <thead>
                        <tr>
                            <th><%= question.content %></th>
                            <th>User Email</th>
                        </tr>
                      </thead>
                      <tbody>
              <% end %>

                  <% answer.responses.each do |response| %>
                          <% if answer.content.split(':')[0] == "check" %>
                                  <% flag = 1 %>
                            <% if response.content.eql?("1")%>
                                  <% count += 1 %>
                            <% end %>
                          <% elsif answer.content.split(':')[0] == "radio" %>
                                  <% flag = 1 %>
                            <% if response.content.eql?("1") %>
                                    <% count += 1 %>
                                <% end %>
                          <% else %>
                                    <tr>
                                      <td><%= response.content %></td>
                                      <td><%= response.user.email %></td>
                                    </tr>
                          <% end %>
                  <% end %>
                  <% if flag == 1 %>
                  <%= answer.content.split(':').slice(1..-1).map(&:inspect).join(' ').to_s.gsub('"', '') %> - <%= count %><br>
                  <% end %>

              <% if answer.content.split(':')[0] != ("check" and "radio") %>
                      </tbody>
                      </table>
              <% end %>

        <% end %>
            <% if flag == 1 %>
                  <div id="<%= question.id %>"></div>
                  <script type="text/javascript">drawChart('<%= question.id %>');</script>
               <% flag = 0 %>
            <% end %>
<% end %>
</div>